### PR TITLE
fix check for 0 || non-zero

### LINKED ISSUE #18: redirects: 0 doesnt work
https://github.com/cojs/cogent/blame/master/lib/index.js#L38

`var redirects = 0 || 3;`

is always **3** ! lol

### PR DESCRIPTION
**Pull request by timaschew**
fixes https://github.com/cojs/cogent/issues/18

btw: **I** found this issue! @KenanSulayman :stuck_out_tongue_closed_eyes:

### CODE REVIEW

**Comment by timaschew** [comment]
you're a cheater!

**Comment by jonathanong** [comment]
wat

**Comment by jonathanong** [comment]
@timaschew gonna add you as a maintainer

**Comment by 19h** [comment]
Ha, he was betting on that ^_o @jonathanong wat wat?

**Pull request merged**
